syntax = "proto3";
package meshtastic;
option java_package = "com.loremote.app.proto";
option java_outer_classname = "MeshProtos";
option optimize_for = LITE_RUNTIME;

message Data {
  int32  portnum  = 1;
  bytes  payload  = 2;
  fixed32 from    = 4;
  fixed32 to      = 5;
}

message MeshPacket {
  fixed32 from      = 1;
  fixed32 to        = 2;
  bytes  decoded   = 4;
  fixed32 id        = 9;
  uint32 rx_time   = 11;
  float  rx_snr    = 13;
  int32  rx_rssi   = 14;
  uint32 hop_limit = 10;
  bool want_ack  = 12;
  uint32 channel   = 8;
}

message FromRadio {
  oneof payload_variant {
    MeshPacket packet         = 2;
    MyNodeInfo my_info        = 3;
    NodeInfo node_info        = 4;
    uint32 config_complete_id = 6;
  }
}

message ToRadio {
  oneof payload_variant {
    MeshPacket packet       = 1;
    uint32 want_config_id   = 3;
  }
}

message MyNodeInfo {
  uint32 my_node_num = 1;
}

message NodeInfo {
  uint32 num = 1;
}
